version: '3'

services:
  database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres_for_testing
      - POSTGRES_PASSWORD=postgres_for_testing
      - POSTGRES_DB=test_db
  s3local:
    image: 'scality/s3server'
    ports:
      - "8000:8000"
    volumes:
      - "./config.json:/usr/src/app/config.json"
  core:
    build:
      context: ../
      dockerfile: backend/core/docker/TestingDockerfile
    ports:
      - "80:80"
  worker:
    build:
      context: ../
      dockerfile: backend/worker/docker/TestingDockerfile
    ports:
      - "81:80"
  test:
    build:
      context: .
      dockerfile: test/Dockerfile
