global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'core'
    scrape_interval: 5s
    static_configs:
      - targets: [core:8080]
        labels:
          group: 'production'

  - job_name: 'worker'
    scrape_interval: 5s
    static_configs:
      - targets: [worker]
        labels:
          group: 'production'

  - job_name: 'push'
    scrape_interval: 5s
    static_configs:
      - targets: [push]
        labels:
          group: 'production'