name: Backend workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_an_publish_docker:
    name: Building and publishing backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build core executable
        run: ./gradlew :backend:core:build
      - name: Copy zip to root
        run: cp -r backend/core/build/distributions/core*.zip core.zip
      - uses: actions/upload-artifact@master
        with:
          name: core_zip
          path: core.zip
          retention-days: 1
      - name: Unzipping distributions
        run: unzip core.zip -d tmp
      - name: Move
        run: mv tmp/core* ./core
      - name: Makedirs
        run: mkdir backend/core/docker/build_dir/
      - name: Copy executables to docker build directory
        run: cp -r auth backend/core/docker/build_dir/core
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.REGISTRY_KEY }}
      - name: Building docker
        run: cd backend/core/docker && docker build . --network=host -t cr.yandex/crp9sskk3fu52ukovaco/ethno-core:$(git rev-parse --short HEAD)
      - name: Pushing docker
        run: docker push cr.yandex/crp9sskk3fu52ukovaco/ethno-core:$(git rev-parse --short HEAD)
