name: Backend workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'revisions.json'
      - '.github/workflows/roll_core_update.yaml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'revisions.json'
      - '.github/workflows/roll_core_update.yaml'

jobs:
  build_an_publish_docker:
    name: Building and publishing backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: build core executable
        run: ./gradlew :backend:core:build
      - name: Copy zip to root
        run: cp -r backend/core/build/distributions/core*.zip core.zip
      - uses: actions/upload-artifact@master
        with:
          name: core_zip
          path: core.zip
          retention-days: 1
      - name: Unzipping distributions
        run: unzip core.zip -d tmp
      - name: Move
        run: mv tmp/core* ./core
      - name: Makedirs
        run: mkdir backend/core/docker/build_dir/
      - name: Copy executables to docker build directory
        run: cp -r core backend/core/docker/build_dir/core
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.REGISTRY_KEY }}
      - name: Exporting env variables
        run: python3 tools/bundle_env_vars.py --configuration backend/core/docker/env_vars_config.json --output backend/core/docker/env.sh
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DBNAME: ${{ secrets.DB_DBNAME }}
          DB_SERVER: rc1c-rj0lqxik0r20u80e.mdb.yandexcloud.net
          DB_PORT: 6432
          JWT_AUDIENCE: ethnosurvey.com
          JWT_REALM: ethnosurvey.com
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_DOMAIN: ethnosurvey.com
          SECURITY_SALT: ${{ secrets.SECURITY_SALT }}
          S3_REGION: ru-central1
          S3_ACCESS_KEY: ${{ secrets.S3_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          S3_URI: https://storage.yandexcloud.net
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          SELF_URI: https://ethnosurvey.com
          WORKER_URI: http://survey-worker.ru-central1.internal
          PUSH_URI: http://survey-push.ru-central1.internal
      - name: Installing YC util
        run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yandex-cloud -n
      - name: Authorizing YC util
        run: source /opt/yandex-cloud/path.bash.inc && echo $SERVICE_KEY>service_key.json && yc config profile create sa-profile && yc config set service-account-key service_key.json && yc config set cloud-id $YC_CLOUD_ID && yc config set folder-id $YC_FOLDER_ID
        env:
          SERVICE_KEY: ${{ secrets.REGISTRY_KEY }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      - name: Getting ssl keychain
        run: |
          source /opt/yandex-cloud/path.bash.inc &&
          yc certificate-manager certificate content --id $CERT_ID --chain backend/core/docker/build_dir/certificate_full_chain.pem --key backend/core/docker/build_dir/private_key.pem
        env:
          CERT_ID: ${{ secrets.CERT_ID }}
      - name: Building docker
        run: cd backend/core/docker && chmod +x runner.sh && docker build . --network=host -t cr.yandex/crp9sskk3fu52ukovaco/ethno-core:$(git rev-parse --short HEAD)
      - name: Pushing docker
        run: docker push cr.yandex/crp9sskk3fu52ukovaco/ethno-core:$(git rev-parse --short HEAD)
