name: "Backend: Upload Config"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Uploading Config"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pushing to s3
        run: aws --endpoint-url=https://storage.yandexcloud.net s3 cp backend/config.json s3://ethnosurvey-config
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_DEFAULT_REGION: ru-central1
