name: Rolling updates
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rolling_updates:
    name: Rolling everything updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Storing ssh key file
        run: echo "$SSH_KEY" > ssh_key && chmod 700 ./ssh_key
        env:
          SSH_KEY: ${{ secrets.CORE_SSH_KEY }}
      - name: Installing YC util
        run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yandex-cloud -n
      - name: Authorizing YC util
        run: source /opt/yandex-cloud/path.bash.inc && echo $SERVICE_KEY>service_key.json && yc config profile create sa-profile && yc config set service-account-key service_key.json && yc config set cloud-id $YC_CLOUD_ID && yc config set folder-id $YC_FOLDER_ID
        env:
          SERVICE_KEY: ${{ secrets.REGISTRY_KEY }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      - name: List instances
        run: source /opt/yandex-cloud/path.bash.inc && yc compute instance list
      - name: Install requirements
        run: pip3 install -r tools/requirements.txt
      - name: Launching core rolling
        run: source /opt/yandex-cloud/path.bash.inc && python3 tools/roll.py core ./services.json ./ssh_key ${{ secrets.YC_TOKEN }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          NOTIFY_CHAT_IDS: ${{ secrets.NOTIFY_CHAT_IDS }}
      - name: Launching worker rolling
        run: source /opt/yandex-cloud/path.bash.inc && python3 tools/roll.py worker ./services.json ./ssh_key ${{ secrets.YC_TOKEN }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          NOTIFY_CHAT_IDS: ${{ secrets.NOTIFY_CHAT_IDS }}
      - name: Launching metrics rolling
        run: source /opt/yandex-cloud/path.bash.inc && python3 tools/roll.py metrics ./services.json ./ssh_key ${{ secrets.YC_TOKEN }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          NOTIFY_CHAT_IDS: ${{ secrets.NOTIFY_CHAT_IDS }}
      - name: Launching metrics rolling
        run: source /opt/yandex-cloud/path.bash.inc && python3 tools/roll.py core,worker,metrics ./services.json ./ssh_key ${{ secrets.YC_TOKEN }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          NOTIFY_CHAT_IDS: ${{ secrets.NOTIFY_CHAT_IDS }}
