name: Test export commited to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing_backend:
    name: Testing backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: copy exported.ts to tmp
        run: mkdir tmp && cp ./web/src/data/exported.ts tmp/exported.ts
      - name: run export
        run: ./export_ts_types.sh
      - name: check diff
        run: diff ./web/src/data/exported.ts tmp/exported.ts && echo OK
