name: Test export commited to main

on:
  push:
    branches:
      - main
    paths:
      - common/data/**
      - util/exporter/**
  pull_request:
    branches:
      - main
    paths:
      - common/data/**
      - util/exporter/**

jobs:
  checking_export_not_changed:
    name: Testing export not changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: copy exported.ts to tmp
        run: mkdir tmp && cp ./web/src/data/exported.ts tmp/exported.ts
      - name: run export
        run: ./export_ts_types.sh
      - name: check diff
        run: diff ./web/src/data/exported.ts tmp/exported.ts && echo OK
