name: Backend workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing_backend:
    name: Testing backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: testing
        run: cd backend && ./full_suit.sh
